name: Frontend Build Pipeline

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
      - run: npm install -g pnpm@10
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
